app:
  version: @project.version@

server:
  port: 8000


# ===== Rabbit MQ =====

# ===== Logging =======
spring:
#  main:
#    banner-mode: "off"
  banner:
    location: classpath:/banner.txt

  rabbitmq:
    host: 127.0.0.1
#    port: 8100
    username: guest
    password: guest



# ===== Swagger ======
# See ru.redsquid.examples.ms.order.config.SwaggerConfig
#
# json output
# http://localhost:8000/v2/api-docs
# ui
# http://localhost:8000/swagger-ui/index.html

