app:
  version: @project.version@

server:
  port: 8000

# ===== Logging =======
spring:
#  main:
#    banner-mode: "off"
  banner:
    location: classpath:/banner.txt
  # ===== Datasource =====
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://order-db:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:liquibase/liquibase-changelog.xml
    enabled: true
  # ===== Rabbit MQ =====
  rabbitmq:
    host: rabbit
#    port: 8100
    username: guest
    password: guest



# ===== Swagger ======
# See ru.redsquid.examples.ms.order.config.SwaggerConfig
#
# json output
# http://localhost:8000/v2/api-docs
# ui
# http://localhost:8000/swagger-ui/index.html

